#!/bin/bash

touch tmp.txt

echo "sbook.txt == cbook.txt ?"
sort cbook.txt > tmp.txt
cmp sbook.txt tmp.txt
if [[ $? -eq 0 ]]; then
    echo "Yes"
else
    echo "No"
fi

echo "sbook.txt == reserved in slog.txt ?"
sed -nre 's/[0-9]+-[0-9]+-[0-9]+:( +[0-9]+)+ +-(( +[0-9]+)+)/\2/p' slog.txt | tr " " "\n" | sed -re '/^$/d' | sort > tmp.txt
cmp sbook.txt tmp.txt
if [[ $? -eq 0 ]]; then
    echo "Yes"
else
    echo "No"
fi

echo "cbook.txt == reserved in clog.txt ?"
sed -nre 's/[0-9]+ [0-9]+.[0-9]+ ([0-9]+)/\1/p' clog.txt | tr " " "\n" | sed -re '/^$/d' | sort > tmp.txt
sort cbook.txt | cmp tmp.txt
if [[ $? -eq 0 ]]; then
    echo "Yes"
else
    echo "No"
fi

exit 0
